vacancies_project/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("applicant-profile/", views.applicant_profile, name="applicant_profile"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("add-experience/", views.add_experience, name="add_experience"),
    path("edit-experience/<int:pk>/", views.experience_edit, name="edit_experience"),
    path("delete-experience/<int:pk>/", views.experience_delete, name="delete_experience"),

]

vacancies_project/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    ApplicantFeedBacksViewSet,
    ApplicantRegistration,
    EmployerRegistration,
    EmpoyerFeedBacksViewSet,
    ExperienceViewSet,
    SendFeedBackViewSet,
    VacancyViewSet,
)

router = DefaultRouter()

router.register("vacancies", VacancyViewSet, basename="vacancies")
router.register(
    r"vacancies/(?P<vacancy_id>\d+)/feedback", SendFeedBackViewSet, basename="feedback"
)
router.register(
    "applicant-feed", ApplicantFeedBacksViewSet, basename="applicant_feedback"
)
router.register("employer-feed", EmpoyerFeedBacksViewSet, basename="employer_feedback")
router.register("experience", ExperienceViewSet, basename="experience")

urlpatterns = [
    path("", include(router.urls)),
    path("reg_employer/", EmployerRegistration.as_view()),
    path("reg_applicant/", ApplicantRegistration.as_view()),
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.jwt")),
]

vacancies_project/vacancies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "vacancies"

urlpatterns = [
    path("vacancies/", views.index, name="index"),
    path("vacancies/<int:pk>/", views.vacancy_detail, name="vacancy_detail"),
    path("vacancies/<int:pk>/feedback/", views.send_feedback, name="feedback"),
    path("apl-feedback/", views.feedback_list, name="applicant_feedback"),
    path("del-apl-feedback/<int:pk>/", views.del_applicant_feedback, name="del_applicant_feedback"),
    path("empl-feedback/", views.employer_feedback_list, name="employer_feedback"),
    path("create-vacancy/", views.create_vacancy, name="create_vacancy"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vacancies_project/vacancies_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Job API",
        default_version="v1",
        description="Документация сервиса с вакансиями",
        # terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@job.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("vacancies.urls")),
    path("", include("accounts.urls")),
    path("api/", include("api.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

vacancies_project/templates/applicant_feedback.html
<!DOCTYPE html>
<html lang="ru">
<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>Вакансии</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>
<blockquote class="blockquote text-center">
 <h1>Мои отклики</h1>
</blockquote>

{% for feedback in feedbacks %}
  <div class="row container gy-5">
    <div class="card col-9 text-center p-3 border bg-light">


        <div <h2>
        <a href = "{% url 'vacancies:vacancy_detail' feedback.vacancy.pk%}">{{ feedback.vacancy.title }}</a></h2>
        </div>

            <h6>{{ feedback.vacancy.company.company_name }}</h6>
            <h6>{{ feedback.vacancy.company.email }}</h6>
            <h6>{{ feedback.vacancy.company.city }}</h6>
            <h6>{{ feedback.vacancy.company.phone_number }}</h6>
            <div class="card-body">
                      <form action="{% url 'vacancies:del_applicant_feedback' feedback.id %}">
                        <button class="btn btn-outline-danger">
                        Удалить запись
                        </button>
                      </form>
            </div>
        </div>

    </div>


{% endfor %}

</body>

</html>

vacancies_project/templates/applicant_profile.html
<!DOCTYPE html>
<html lang="ru">
<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>Вакансии</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>
    {% if is_applicant == True %}
      <div class="card col text-right p-3 border bg-light">
          <p>
              <a href = "{% url 'accounts:add_experience' %}" class="btn btn-primary">Добавить место работы</a>
          </p>
      </div>
      <blockquote class="blockquote text-center">
       <h1>{{ applicant.get_full_name }}</h1>
      </blockquote>

      {% for experience in experiences %}
        <div class="row container gy-5">
          <div class="card col-9 text-center p-3 border bg-light">
                <h5 class="card-header"> {{ experience.company_name }} </h5>
                <div class="card-body">
                  <p>
                    <h5>Начало работы</h5>
                    {{ experience.start_date }}
                  </p>
                  <p>
                    <h5>Окончание работы</h5>
                    {{ experience.finish_date }}
                  </p>
                  <h5 class="card-subtitle">Результаты</h5>
                  <p>{{ experience.job_results }}</p>
                </div>
              <div class="card-body">
                  <form action="{% url 'accounts:edit_experience' experience.id %}">
                    <button class="btn btn-outline-primary">
                    Редактировать запись
                    </button>
                  </form>
              </div>
              <div class="card-body">
                  <form action="{% url 'accounts:delete_experience' experience.id %}">
                    <button class="btn btn-outline-danger">
                    Удалить запись
                    </button>
                  </form>
              </div>
          </div>

        {% endfor %}
    {% else %}
            <div class="blockquote text-center">
              <h3> Упс! Похоже вам сюда не нужно </h3>
            </div>
    {% endif %}

</body>

</html>

vacancies_project/templates/create_experience.html
<!DOCTYPE html>
<html lang="ru">

<title>Добавить место работы</title>

<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>{{ vacancy.title }}</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Добавить место работы
        </div>
        <div class="card-body">

         <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>
            {{ field }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          {% endfor %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Добавить
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
</body>
</html>

vacancies_project/templates/create_vacancy.html
<!DOCTYPE html>
<html lang="ru">

<title>Опубликовать вакансию</title>

<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>{{ vacancy.title }}</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Опубликовать вакансию
        </div>
        <div class="card-body">

         <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>
            {{ field }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          {% endfor %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Опубликовать
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
</body>
</html>

vacancies_project/templates/employer_feedback.html
<!DOCTYPE html>
<html lang="ru">
<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>Отклики</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>
<blockquote class="blockquote text-center">
 <h1>Отклики</h1>
</blockquote>

{% for feedback in feedbacks %}
  <div class="row container py-4">
    <div class="card col-12 text-right p-3 border bg-light">
         <h5 class="card-header">
        <a href = "{% url 'accounts:profile' feedback.applicant.id %}">{{ feedback.applicant.get_full_name }}</a></h5>
          <div class="card-body">
              <p>
                  <h6>{{ feedback.applicant.city }}</h6>
              </p>
              <p>
                  <h6>{{ feedback.applicant.email }}</h6>
              </p>
              <p>
                  <h6>{{ feedback.applicant.phone_number }}</h6>
              </p>
              <p>
                  <h6>{{ feedback.applicant.tg_link }}</h6>
              </p>
              <p>
                  <h6>{{ feedback.applicant.vk_link }}</h6>
              </p>
          </div>


    </div>
  </div>


{% endfor %}

</body>

</html>

vacancies_project/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>Вакансии</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>
<blockquote class="blockquote text-center">
 <h1>Vacancies</h1>
</blockquote>

{% for vacancy in vacancies %}
  <div class="row container gy-5">
    <div class="card col-9 text-center p-3 border bg-light">


          <h5 class="card-header"> {{ vacancy.title }} </h5>
          <div class="card-body">
            <p>
              <h5>Зарплата</h5>
              {{ vacancy.salary }}
            </p>
            <h5 class="card-subtitle">Описание</h5>
            <p>{{ vacancy.description }}</p>
          </div>
    </div>
    <div class="card col-3 p-3 border bg-light">
       <p>{{ vacancy.company }}</p>
        <p>
             <a href = "{% url 'vacancies:vacancy_detail' vacancy.pk%}" class="btn btn-primary">Читать целиком</a>
        </p>
    </div>

{% endfor %}

</body>

</html>

vacancies_project/templates/navbar.html
<html>
<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>Вакансии</title>

</head>
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link "
            href="">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
          href="">Технологии</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light"
          href="">Выйти</a>
        </li>
        <li>
          Пользователь
        <li>

        <li class="nav-item">
          <a class="nav-link link-light "
          href="">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light"
          href="">Регистрация</a>
        </li>
      </ul>
    </div>
  </nav>
</header>

</html>

vacancies_project/templates/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>Вакансии</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>
 <div class="row container gy-5">
     <div class="card text-left p-4 border bg-light">
      <blockquote class="blockquote text-center">
                <h1>{{ applicant.get_full_name }}</h1>
      </blockquote>



            <p>
                  <h6>Город: {{ applicant.city }}</h6>
              </p>
              <p>
                  <h6>Почта: {{ applicant.email }}</h6>
              </p>
              <p>
                  <h6>Номер телефона: {{ applicant.phone_number }}</h6>
              </p>
              <p>
                  <h6>Ник в телеграм: {{ applicant.tg_link }}</h6>
              </p>
              <p>
                  <h6>Профиль в vk: {{ feedback.applicant.vk_link }}</h6>
              </p>
        </div>
 </div>
<br>
<div class="text-center ">
    <h3> Опыт работы </h3>
</div>
{% for experience in experiences %}
  <div class="row container gy-5">
    <div class="card col-9 text-center p-3 border bg-light">

          <h5 class="card-header"> {{ experience.company_name }} </h5>
          <div class="card-body">
            <p>
              <h5>Начало работы</h5>
              {{ experience.start_date }}
            </p>
            <p>
              <h5>Окончание работы</h5>
              {{ experience.finish_date }}
            </p>
            <h5 class="card-subtitle">Результаты</h5>
            <p>{{ experience.job_results }}</p>
          </div>
    </div>
{% endfor %}

</body>

</html>

vacancies_project/templates/vacancy_detail.html
<html>
{% load static %}
{% load thumbnail %}

<head>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous">


  <meta charset="utf-8">
  <meta name="description" content="Краткое описание страницы">
  <title>{{ vacancy.title }}</title>

</head>

<body>
<header>
      {% include 'includes/header.html' %}
</header>
<div class="row">

  <h4 class="card  text-center"> {{ vacancy.title }} </h4>

    <div class="col-6 card-body text-left">

        <p>
          <h5>Зарплата</h5>
          {{ vacancy.salary }}
        </p>
      <h5 class="card-subtitle">Описание</h5>
      <p>{{ vacancy.description }}</p>
    </div>
    <div class="col-3">

         <h3>{{ vacancy.company }}</h3>
        {% thumbnail vacancy.image "300x200" crop="left" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <br>
        <h4>{{ vacancy.company.about }}</h4>
        <div <h3> Наши контакты </h3>
            <h5>{{ vacancy.company.email }}</h5>
            <h5>{{ vacancy.company.city }}</h5>
            <h5>{{ vacancy.company.addres }}</h5>
            <h5>{{ vacancy.company.phone_number }}</h5>
            <h5>{{ vacancy.company.address }}</h5>
            <h5>{{ vacancy.company.tg_link }}</h5>
            <h5>{{ vacancy.company.vk_link }}</h5>


        </div>

        {% if request.user.is_authenticated and is_applicant == True and is_sent == False  %}

                <p>
                    <a href ="{% url 'vacancies:feedback' vacancy.pk%}" class="btn btn-primary">Откликнуться</a>
                </p>

        {% endif %}
    </div>

    <div class="col-3 text-center">

    </div>
</div>

</body>
</html>