vacancies_project/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("applicant-profile/", views.applicant_profile, name="applicant_profile"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("add-experience/", views.add_experience, name="add_experience"),
    path("edit-experience/<int:pk>/", views.experience_edit, name="edit_experience"),
    path("delete-experience/<int:pk>/", views.experience_delete, name="delete_experience"),

]

vacancies_project/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    ApplicantFeedBacksViewSet,
    ApplicantRegistration,
    EmployerRegistration,
    EmpoyerFeedBacksViewSet,
    ExperienceViewSet,
    SendFeedBackViewSet,
    VacancyViewSet,
)

router = DefaultRouter()

router.register("vacancies", VacancyViewSet, basename="vacancies")
router.register(
    r"vacancies/(?P<vacancy_id>\d+)/feedback", SendFeedBackViewSet, basename="feedback"
)
router.register(
    "applicant-feed", ApplicantFeedBacksViewSet, basename="applicant_feedback"
)
router.register("employer-feed", EmpoyerFeedBacksViewSet, basename="employer_feedback")
router.register("experience", ExperienceViewSet, basename="experience")

urlpatterns = [
    path("", include(router.urls)),
    path("reg_employer/", EmployerRegistration.as_view()),
    path("reg_applicant/", ApplicantRegistration.as_view()),
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.jwt")),
]

vacancies_project/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path("login/", LoginView.as_view(template_name="users/log_in.html"), name="login"),
    path("employer-signup/", views.employer_registration, name="employer-signup"),
    path("applicant-signup/", views.applicant_registration, name="applicant-signup"),
]

vacancies_project/vacancies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "vacancies"

urlpatterns = [
    path("vacancies/", views.index, name="index"),
    path("vacancies/<int:pk>/", views.vacancy_detail, name="vacancy_detail"),
    path("vacancies/<int:pk>/feedback/", views.send_feedback, name="feedback"),
    path("apl-feedback/", views.feedback_list, name="applicant_feedback"),
    path("del-apl-feedback/<int:pk>/", views.del_applicant_feedback, name="del_applicant_feedback"),
    path("empl-feedback/", views.employer_feedback_list, name="employer_feedback"),
    path("create-vacancy/", views.create_vacancy, name="create_vacancy"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vacancies_project/vacancies_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Job API",
        default_version="v1",
        description="Документация сервиса с вакансиями",
        # terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@job.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("vacancies.urls")),
    path("", include("accounts.urls")),
    path("api/", include("api.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

vacancies_project/templates/includes/header.html
<!DOCTYPE html>
<html lang="ru">


<header>
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link "
            href="{% url 'vacancies:index' %}">Вакансии</a>
        </li>
        </li>
        {% if request.user.is_authenticated %}
          {% if is_applicant == False %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vacancies:create_vacancy' %}">Новая вакансия</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vacancies:employer_feedback' %}">Отклики соискателей</a>
            </li>

          {% elif is_applicant == True %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vacancies:applicant_feedback' %}">Мои отклики</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:applicant_profile' %}">Профиль</a>
            </li>
          {% endif %}

          <li class="nav-item">
                    <a class="nav-link link-light"
                    href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
            href="{% url 'users:login' %}">Войти</a>

          <li class="nav-item">
            <a class="nav-link link-light"
            href="{% url 'users:applicant-signup' %}">Регистрация соискателя</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light"
            href="{% url 'users:employer-signup' %}">Регистрация работодателя</a>
          </li>
        {% endif %}
      {% endwith %}
      </ul>
    </div>
  </nav>
  </header>
</html>